name: Build Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        ava-version: '17'
        java-package: jdk
        architecture: x64
        distribution: 'temurin'  # Specify JDK distribution here
        check-latest: false

    # Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build the project using Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Upload the JAR artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app-jar
        path: target/*.jar
